### ISSUE TITLE
401 error running Demo

### ISSUE THREAD

**Issue by alanrose** [mokrayaGISka/cesium_measurementTool#2]
401 error 
 https://api.cesium.com/v1/assets/2/endpoint?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwMzJhNTk5NS1lMTc5LTQ0MWMtYTc3Mi1lZmE3NjYyZWMwMzAiLCJpZCI6MjU5LCJzY29wZXMiOlsiYXNyIiwiZ2MiXSwiaWF0IjoxNTY5OTMyNDcwfQ.ifTZn9zZ4Tc3UD6yqH8yqwyU-8OgFQN2cqno6HmxWGw 401

**Comment by mokrayaGISka** [comment]
Hi,
Fixed now by adding default access token
Thank you
